# Generated by Django 6.0.3 on 2026-04-05 20:20

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('leetcode_url', models.URLField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('topic_tag', models.CharField(max_length=100)),
                ('step_number', models.IntegerField()),
                ('order_in_step', models.IntegerField()),
                ('module', models.CharField(default='striver', max_length=20)),
                ('pattern_name', models.CharField(blank=True, max_length=100)),
                ('pattern_explanation', models.TextField(blank=True)),
                ('python_template', models.TextField(blank=True)),
                ('java_template', models.TextField(blank=True)),
                ('time_complexity', models.CharField(blank=True, max_length=50)),
                ('space_complexity', models.CharField(blank=True, max_length=50)),
                ('ai_generated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAssignment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('solved', models.BooleanField(default=False)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('points_awarded', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
        ),
    ]
